---
name: Template based CI workflow
'on':
  # pull_request:
  # schedule:
  #   - cron: "0 4 * * 5"
  push:
    branches:
      - main
      - master
    tags:
      - '*'

defaults:
  # env:
  #   GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
  run:
    working-directory: 'sleif.ws'

jobs:
  build:
    environment: build
    uses: sleif/workflow_templates/.github/workflows/ci-template_ansible-lint-galaxy.yml@main
    # runs-on: ubuntu-latest
    # steps:
    #   - name: include template
    #     # env:
    #     #   GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
    #     run: |
    #       echo "API: $GALAXY_API_KEY"
    #   - name: Template workflow
